### ISSUE TITLE
Working principles plugin.

### ISSUE THREAD

**Issue by ghost** [leecrossley/cordova-plugin-apple-watch#11] opened 2015-05-27 14:04 UTC
Hello, I want to use your plugin because I use cordova and i-watch. I read the guide but I don't understand the working principles of this plugin. In the official apple guide I read this:

Apple Watch requires the presence of an iPhone to run third-party apps. To create a third-party app, you need two separate bundles: a WatchKit app (that runs on Apple Watch) and a WatchKit extension (that runs on the user’s iPhone). The WatchKit app contains only the storyboards and resource files associated with your app’s user interface. The WatchKit extension contains the code for managing the WatchKit app’s user interface and for responding to user interactions.

Now I don't understand where I have to write my code. Where do I have to write my WatchKit app and WatchKit extension? Sorry...Can you write the short example for understand how it works. Thanks!

**Comment by leecrossley** [comment] 2015-06-03 15:49
Duplicate of #13

**Closed as completed by leecrossley** 2015-06-03 15:49 UTC
